### ISSUE TITLE
[BUG] Some webhook alerts are not reaching to MSTeam

### ISSUE THREAD

**Issue by yogeshbidari** [prometheus-msteams/prometheus-msteams#146] opened 2020-08-05 16:11 UTC
**Describe the bug**
We have around 11 alerts triggering to MSTeams. We are getting only 9-10 alerts in the MSTeams.

**Version**
1.3.5
Using helm to deploy

**To Reproduce**
Triggering multiple alerts at same time.

**Expected behavior**
Should send all the alerts to MSTeams

**Additional context**
Sometimes we see error in the pod logs.
Most of the time, the response code is 200. Still the alerts won't reflect in MSTeams.

Error log:
```
{"caller":"logging.go:25","err":null,"level":"debug","response_message":"Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 412 with ContextId tcid=4057701493317325833,server=MA1PEPF00000153,cv=Bvz5psb3A06lNnEvglySWQ.1.0,MS-CV=Bvz5psb3A06lNnEvglySWQ.1.0..","response_status":200,"ts":"2020-08-05T15:56:47.769709699Z","webhook_url":"https://outlook.office.com/webhook/xxxxxxxxxxx"}
{"caller":"transport.go:52","host":"prometheus-msteams:2000","method":"POST","status":200,"took":"2.048191303s","ts":"2020-08-05T15:56:47.769991574Z","uri":"/alertmanager"}
```

**Comment by Knappek** [comment] 2020-08-11 20:27
Thanks for reporting this issue. 

What is sad is that apparently MS Teams webhook returns with a `200` although it is actually a `412` according to the message. It is hard to guess what could be the root cause for this. Could you provide the teams message that is being sent to the webhook? Is it really "sometimes" failing, or always with the same teams message?

**Comment by mtherreault** [comment] 2021-03-24 13:19
The status of the HTTP response when calling webhooks is never checks and a `200` is always returned, Alertmanager is  never aware that the notification has failed, so never retried. And unfortunately, the result of HTTP responses of called webhooks is only logged when debug logging is enabled.

So I had an invalid MsTeams webhook URL (which resulted in a 400) and never had any sign of error anywhere.

And I am using latest version 1.4.2.

**Comment by mtherreault** [comment] 2021-03-24 13:27
Hopefully I can use the metric time series `http_client_completed_count` to track for webhook HTTP request errors.

**Comment by Knappek** [comment] 2021-03-25 07:31
> The status of the HTTP response when calling webhooks is never checks and a 200 is always returned

That is not intended and I can't reproduce this behaviour. Looking into the code we are handling the response status [here](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/pkg/service/service.go#L93). I also just tested to send to a non-existing webhook url and received a `4xx` status. As said, in your particular use case, the MS teams API returned with a message having `412` in it, but the actual status code seemed to be `200` (see `"response_status":200` in your log message). At first glance, this looks like a bug in the teams API to me.

> So I had an invalid MsTeams webhook URL (which resulted in a 400) and never had any sign of error anywhere.

I can't reproduce this. Could you give me some details how you tested that and how I can reproduce this behaviour?

**Comment by mtherreault** [comment] 2021-03-25 21:56
@Knappek you are right I did not see that the status of the request to Ms Teams API was checked (not really ignored). However the result of the request (or requests in case of a [card split](https://github.com/prometheus-msteams/prometheus-msteams/blob/v1.4.2/pkg/service/service.go#L51)), including the status, is returned as serialized data in body of the response to Alertmanager, and the actual response is (except for a network failure) [always 200](https://github.com/prometheus-msteams/prometheus-msteams/blob/v1.4.2/pkg/transport/transport.go#L93).

Sadly Alertmanager does not interpret the content of the response of a call to a webhook, it is simply [ignored](https://github.com/prometheus/alertmanager/blob/master/notify/webhook/webhook.go#L118).

For the `400`, we met it because we had minor typo in the URL path of a webhook. Here a (URL obfuscated) `curl` output showing the error returned by Ms Teams API:
```
> POST /webhookb2/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX@XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/IncomingWebhook/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX HTTP/1.1
> Host: ubisoftaad.webhook.office.com
> User-Agent: curl/7.73.0-DEV
> Accept: */*
> Content-Length: 1167
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 1167 out of 1167 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 19
< Content-Type: text/plain; charset=utf-8
< Expires: -1
< Server: Microsoft-IIS/10.0
< request-id: 1d133cb6-9167-467a-ae29-f98f2830cd85
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-CalculatedFETarget: BN8PR12CU001.internal.outlook.com
< X-BackEndHttpStatus: 400
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-FEProxyInfo: BN8PR12CA0034.NAMPRD12.PROD.OUTLOOK.COM
< X-CalculatedBETarget: BN0PR08MB6901.NAMPRD08.PROD.OUTLOOK.COM
< X-BackEndHttpStatus: 400
< X-AspNet-Version: 4.0.30319
< X-CafeServer: BN8PR12CA0034.NAMPRD12.PROD.OUTLOOK.COM
< X-BEServer: BN0PR08MB6901
< X-RUM-Validated: 1
< X-Proxy-RoutingCorrectness: 1
< X-Proxy-BackendServerStatus: 400
< X-FEServer: BN8PR12CA0034
< X-Powered-By: ASP.NET
< X-FEServer: QB1PR01CA0002
< Date: Thu, 25 Mar 2021 21:49:02 GMT
<
* Connection #0 to host proxy.ubisoft.org left intact
Invalid webhook URL
```

**Comment by bzon** [comment] 2021-03-25 22:30
The reason why the prometheus-msteams status code is always 200 is because the http call was sent OK regardless the status code returned to the http client. Note that Alert manager ignores the status code and response of prometheus-msteams too.

There are two ways for you to monitor this. Aggregate webhook error logs or use http_client_roundtrip_latency_count metrics. The status code should be there.

**Comment by mtherreault** [comment] 2021-03-25 22:56
Alertmanager is not completely ignoring status codes returned by webhooks, it manages counters for notification errors and handles retries in case of 5XX errors, but this is not well documented behavior. The actual HTTP call is a success but not the notification, so I guess it depends on now we semantically define as a success.

Anyway we use the `http_client_completed_count` time series to track for these errors.

**Comment by bzon** [comment] 2021-03-25 23:05
In your case, there will be no use for alert-manager to retry a bad request. But for now, using prometheus-msteams http client metric is the only way to get notified that something is wrong.

Though, I think a configurable feature to handle retry on specific status code errors can be handled within prometheus-msteams itself.

Can we close the issue now?

**Comment by mtherreault** [comment] 2021-03-25 23:14
As I have a way to monitor these errors, I'm OK. But I am not the one who has open the issue, I mainly wanted to contribute to the discussion and have better comprehension of the behavior of Prometheus MsTeams.

Thanks for all for your quick feedback and answers!

**Closed** 2021-05-02 12:48 UTC
Labels: bug, question
