### ISSUE TITLE
URL not a hyperlink

### ISSUE THREAD

**Issue by Biomains** [prometheus-msteams/prometheus-msteams#134] opened 2020-06-23 07:55 UTC
I have noticed that when alert "Instance" is a URL, its not displayed as an hyperlink. Which is very useful when we do URL checking.
When alert forwarded to Desktop version of Teams, its not clickable. But in Mobile versions of Teams, it is.

I guess this has nothing to do with promethues-msteams exporter, but maybe there is a solution for this?

**Comment by Knappek** [comment] 2020-06-24 11:25
Hi @Biomains thank you for filing this. Could you please provide the MS teams card template you are using, and the corresponding prometheus alert json?

**Comment by Biomains** [comment] 2020-06-24 12:49
I am using the default template:

{{ define "teams.card" }}
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
                 {{- else if eq .Status "firing" -}}
                    {{- if eq .CommonLabels.severity "critical" -}}8C1A1A
                    {{- else if eq .CommonLabels.severity "warning" -}}FFA500
                    {{- else -}}808080{{- end -}}
                 {{- else -}}808080{{- end -}}",
  "summary": "{{- if eq .CommonAnnotations.summary "" -}}
                  {{- if eq .CommonAnnotations.message "" -}}
                    {{- if eq .CommonLabels.alertname "" -}}
                      Prometheus Alert
                    {{- else -}}
                      {{- .CommonLabels.alertname -}}
                    {{- end -}}
                  {{- else -}}
                    {{- .CommonAnnotations.message -}}
                  {{- end -}}
              {{- else -}}
                  {{- .CommonAnnotations.summary -}}
              {{- end -}}",
  "title": "Prometheus Alert ({{ .Status | title }})",
  "sections": [ {{$externalUrl := .ExternalURL}}
  {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
    {
      "activityTitle": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})",
      "facts": [
        {{- range $key, $value := $alert.Annotations }}
        {
          "name": "{{ $key }}",
          "value": "{{ $value }}"
        },
        {{- end -}}
        {{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}
        {
          "name": "{{ $key }}",
          "value": "{{ $value }}"
        }
        {{- end }}
      ],
      "markdown": true
    }
    {{- end }}
  ]
}
{{ end }}

**Comment by Knappek** [comment] 2020-06-27 07:48
Could you please also provide the Prometheus Alert json that is causing the issue?

**Comment by Biomains** [comment] 2020-06-29 12:23
{"status":"success","data":{"alerts":[{"labels":{"alertname":"critical","instance":"https://TESTING.domain.no","job":"critical","severity":"critical"},"annotations":{},"state":"firing","activeAt":"2020-06-29T13:47:18.649490007+02:00","value":"0e+00"}

**Comment by Knappek** [comment] 2020-06-30 05:28
@Biomains I am able to reproduce it, for it is also not working on the mobile app. This seems to be [an issue at MS Teams](https://techcommunity.microsoft.com/t5/microsoft-teams/some-urls-will-not-transform-into-a-clickable-link-when-entered/m-p/26743). 

Any chance to mark the links as hyperlink at your source using usual markdown hyperlink syntax with `[my link](http://example.com)` or `<a href='http://example.com/'>http://example.com/</a>` ?

**Comment by Knappek** [comment] 2021-05-02 12:49
Closing issue as it is not related to `prometheus-msteams`.

**Closed by Knappek** 2021-05-02 12:49 UTC
Labels: feature, question
